jobs:
  integration:
    name: Integration test
    needs:
    - java11
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle
    - continue-on-error: true
      name: Run integration tests
      run: ./gradlew integrationTest
  java11:
    name: Build with Java 11
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 11
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew check
name: Build SMBJ
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
