jobs:
  java12:
    name: Build with Java 12
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 12
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew check
  release:
    name: Release
    needs:
    - java12
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - continue-on-error: true
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 12
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNINGKEY }}
        ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.SIGNINGKEYID }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNINGPASSWORD }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
      name: Release
      run: ./gradlew clean publishToSonatype closeAndReleaseSonatypeStagingRepository
name: SMBJ Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
permissions:
  contents: write
